// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OpenLR.proto

package joynext.protobuf;

public final class OpenLROuterClass {
  private OpenLROuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenLR_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenLR_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenLR_GeoCoordinate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenLR_GeoCoordinate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenLR_LinearLocationReference_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenLR_LinearLocationReference_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenLR_LinearLocationReference_LineProperties_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenLR_LinearLocationReference_LineProperties_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenLR_LinearLocationReference_PathProperties_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenLR_LinearLocationReference_PathProperties_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenLR_LinearLocationReference_FirstLocationReferencePoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenLR_LinearLocationReference_FirstLocationReferencePoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenLR_LinearLocationReference_IntermediateLocationReferencePoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenLR_LinearLocationReference_IntermediateLocationReferencePoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenLR_LinearLocationReference_LastLocationReferencePoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenLR_LinearLocationReference_LastLocationReferencePoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenLR_AreaLocationReference_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenLR_AreaLocationReference_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenLR_AreaLocationReference_PolygonLocationReference_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenLR_AreaLocationReference_PolygonLocationReference_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014OpenLR.proto\"\235\022\n\006OpenLR\022B\n\027linearLocat" +
      "ionReference\030\001 \001(\0132\037.OpenLR.LinearLocati" +
      "onReferenceH\000\022>\n\025areaLocationReference\030\002" +
      " \001(\0132\035.OpenLR.AreaLocationReferenceH\000\0324\n" +
      "\rGeoCoordinate\022\021\n\tlongitude\030\001 \001(\021\022\020\n\010lat" +
      "itude\030\002 \001(\021\032\276\016\n\027LinearLocationReference\022" +
      "J\n\005first\030\001 \001(\0132;.OpenLR.LinearLocationRe" +
      "ference.FirstLocationReferencePoint\022H\n\004l" +
      "ast\030\002 \001(\0132:.OpenLR.LinearLocationReferen" +
      "ce.LastLocationReferencePoint\022Y\n\rinterme" +
      "diates\030\003 \003(\0132B.OpenLR.LinearLocationRefe" +
      "rence.IntermediateLocationReferencePoint" +
      "\032\251\004\n\016LineProperties\022P\n\023functionalRoadCla" +
      "ss\030\001 \001(\01623.OpenLR.LinearLocationReferenc" +
      "e.FunctionalRoadClass\022K\n\tformOfWay\030\002 \001(\016" +
      "28.OpenLR.LinearLocationReference.LinePr" +
      "operties.FormOfWay\022\017\n\007bearing\030\003 \001(\r\"\346\002\n\t" +
      "FormOfWay\022\027\n\023FORM_OF_WAY_INVALID\020\000\022\031\n\025FO" +
      "RM_OF_WAY_UNDEFINED\020\001\022\030\n\024FORM_OF_WAY_MOT" +
      "ORWAY\020\002\022$\n FORM_OF_WAY_MULTIPLE_CARRIAGE" +
      "WAY\020\003\022\"\n\036FORM_OF_WAY_SINGLE_CARRIAGEWAY\020" +
      "\004\022\032\n\026FORM_OF_WAY_ROUNDABOUT\020\005\022\036\n\032FORM_OF" +
      "_WAY_TRAFFIC_SQUARE\020\006\022\030\n\024FORM_OF_WAY_SLI" +
      "PROAD\020\007\022\025\n\021FORM_OF_WAY_OTHER\020\010\022\031\n\025FORM_O" +
      "F_WAY_BIKE_PATH\020\t\022\030\n\024FORM_OF_WAY_FOOTPAT" +
      "H\020\n\022\037\n\033FORM_OF_WAY_PEDESTRAIN_ZONE\020\013\032|\n\016" +
      "PathProperties\022O\n\022lowestFRCToNextLRP\030\001 \001" +
      "(\01623.OpenLR.LinearLocationReference.Func" +
      "tionalRoadClass\022\031\n\021distanceToNextLRP\030\002 \001" +
      "(\r\032\340\001\n\033FirstLocationReferencePoint\0221\n\022ab" +
      "soluteCoordinate\030\001 \001(\0132\025.OpenLR.GeoCoord" +
      "inate\022F\n\016lineProperties\030\002 \001(\0132..OpenLR.L" +
      "inearLocationReference.LineProperties\022F\n" +
      "\016pathProperties\030\003 \001(\0132..OpenLR.LinearLoc" +
      "ationReference.PathProperties\032\347\001\n\"Interm" +
      "ediateLocationReferencePoint\0221\n\022relative" +
      "Coordinate\030\001 \001(\0132\025.OpenLR.GeoCoordinate\022" +
      "F\n\016lineProperties\030\002 \001(\0132..OpenLR.LinearL" +
      "ocationReference.LineProperties\022F\n\016pathP" +
      "roperties\030\003 \001(\0132..OpenLR.LinearLocationR" +
      "eference.PathProperties\032\227\001\n\032LastLocation" +
      "ReferencePoint\0221\n\022relativeCoordinate\030\001 \001" +
      "(\0132\025.OpenLR.GeoCoordinate\022F\n\016linePropert" +
      "ies\030\002 \001(\0132..OpenLR.LinearLocationReferen" +
      "ce.LineProperties\"\240\002\n\023FunctionalRoadClas" +
      "s\022!\n\035FUNCTIONAL_ROAD_CLASS_INVALID\020\000\022\033\n\027" +
      "FUNCTIONAL_ROAD_CLASS_0\020\001\022\033\n\027FUNCTIONAL_" +
      "ROAD_CLASS_1\020\002\022\033\n\027FUNCTIONAL_ROAD_CLASS_" +
      "2\020\003\022\033\n\027FUNCTIONAL_ROAD_CLASS_3\020\004\022\033\n\027FUNC" +
      "TIONAL_ROAD_CLASS_4\020\005\022\033\n\027FUNCTIONAL_ROAD" +
      "_CLASS_5\020\006\022\033\n\027FUNCTIONAL_ROAD_CLASS_6\020\007\022" +
      "\033\n\027FUNCTIONAL_ROAD_CLASS_7\020\010\032\202\002\n\025AreaLoc" +
      "ationReference\022I\n\007polygon\030\001 \001(\01326.OpenLR" +
      ".AreaLocationReference.PolygonLocationRe" +
      "ferenceH\000\032\217\001\n\030PolygonLocationReference\0226" +
      "\n\027firstCoordinateAbsolute\030\001 \001(\0132\025.OpenLR" +
      ".GeoCoordinate\022;\n\034remainingCoordinatesRe" +
      "lative\030\002 \003(\0132\025.OpenLR.GeoCoordinateB\014\n\nA" +
      "reaMethodB\023\n\021LocationReferenceB\024\n\020joynex" +
      "t.protobufP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_OpenLR_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OpenLR_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenLR_descriptor,
        new java.lang.String[] { "LinearLocationReference", "AreaLocationReference", "LocationReference", });
    internal_static_OpenLR_GeoCoordinate_descriptor =
      internal_static_OpenLR_descriptor.getNestedTypes().get(0);
    internal_static_OpenLR_GeoCoordinate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenLR_GeoCoordinate_descriptor,
        new java.lang.String[] { "Longitude", "Latitude", });
    internal_static_OpenLR_LinearLocationReference_descriptor =
      internal_static_OpenLR_descriptor.getNestedTypes().get(1);
    internal_static_OpenLR_LinearLocationReference_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenLR_LinearLocationReference_descriptor,
        new java.lang.String[] { "First", "Last", "Intermediates", });
    internal_static_OpenLR_LinearLocationReference_LineProperties_descriptor =
      internal_static_OpenLR_LinearLocationReference_descriptor.getNestedTypes().get(0);
    internal_static_OpenLR_LinearLocationReference_LineProperties_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenLR_LinearLocationReference_LineProperties_descriptor,
        new java.lang.String[] { "FunctionalRoadClass", "FormOfWay", "Bearing", });
    internal_static_OpenLR_LinearLocationReference_PathProperties_descriptor =
      internal_static_OpenLR_LinearLocationReference_descriptor.getNestedTypes().get(1);
    internal_static_OpenLR_LinearLocationReference_PathProperties_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenLR_LinearLocationReference_PathProperties_descriptor,
        new java.lang.String[] { "LowestFRCToNextLRP", "DistanceToNextLRP", });
    internal_static_OpenLR_LinearLocationReference_FirstLocationReferencePoint_descriptor =
      internal_static_OpenLR_LinearLocationReference_descriptor.getNestedTypes().get(2);
    internal_static_OpenLR_LinearLocationReference_FirstLocationReferencePoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenLR_LinearLocationReference_FirstLocationReferencePoint_descriptor,
        new java.lang.String[] { "AbsoluteCoordinate", "LineProperties", "PathProperties", });
    internal_static_OpenLR_LinearLocationReference_IntermediateLocationReferencePoint_descriptor =
      internal_static_OpenLR_LinearLocationReference_descriptor.getNestedTypes().get(3);
    internal_static_OpenLR_LinearLocationReference_IntermediateLocationReferencePoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenLR_LinearLocationReference_IntermediateLocationReferencePoint_descriptor,
        new java.lang.String[] { "RelativeCoordinate", "LineProperties", "PathProperties", });
    internal_static_OpenLR_LinearLocationReference_LastLocationReferencePoint_descriptor =
      internal_static_OpenLR_LinearLocationReference_descriptor.getNestedTypes().get(4);
    internal_static_OpenLR_LinearLocationReference_LastLocationReferencePoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenLR_LinearLocationReference_LastLocationReferencePoint_descriptor,
        new java.lang.String[] { "RelativeCoordinate", "LineProperties", });
    internal_static_OpenLR_AreaLocationReference_descriptor =
      internal_static_OpenLR_descriptor.getNestedTypes().get(2);
    internal_static_OpenLR_AreaLocationReference_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenLR_AreaLocationReference_descriptor,
        new java.lang.String[] { "Polygon", "AreaMethod", });
    internal_static_OpenLR_AreaLocationReference_PolygonLocationReference_descriptor =
      internal_static_OpenLR_AreaLocationReference_descriptor.getNestedTypes().get(0);
    internal_static_OpenLR_AreaLocationReference_PolygonLocationReference_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenLR_AreaLocationReference_PolygonLocationReference_descriptor,
        new java.lang.String[] { "FirstCoordinateAbsolute", "RemainingCoordinatesRelative", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
